version: 2.0.{build}
image: Visual Studio 2017

build_script:
  - dotnet restore
  - dotnet build --configuration Release

artifacts:
  - path: '*.nupkg'

after_build:
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }